version: 1.0.{build}
configuration: Release
install:
- ps: >-
    choco install gitversion.portable -pre -y

    Write-Host -NoNewline "Installing NuGet 3.3.0..."


    if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }


    (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe', "$nugetDir\NuGet.exe")


    Write-Host "OK" -ForegroundColor Green
assembly_info:
  patch: false
before_build:
- cmd: nuget restore src
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
test:
  assemblies:
  - '**\*.Tests.dll'
  - '**\*.Specifications.dll'
after_build:
  - cmd: ECHO nuget pack src\Nuget\Tranquire.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack src\Nuget\Tranquire.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"  
  - cmd: ECHO nuget pack src\Nuget\Tranquire.Selenium.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack src\Nuget\Tranquire.Selenium.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Tranquire.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "Tranquire.Selenium.%GitVersion_NuGetVersion%.nupkg"
  
deploy:
- provider: NuGet
  api_key:
    secure: 55uxvHMTDwA2bAKpOX6Wjb/t5eTUsLhsZfJukyEyCboW3c/ZnWHJaz6UeRdPRKVX
  on:
    branch: master